# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# extra configuration
install! 'cocoapods', deterministic_uuids: false, integrate_targets: true

target 'go' do
# Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    # the following ones are the ones takes from "Libraries" in XCode:
    'RCTAnimation',
    'RCTActionSheet',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  # React Native Linear Gradient
  # https://github.com/react-native-community/react-native-linear-gradient
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  
  # React Native Gesture Handler
  # https://github.com/kmagiera/react-native-gesture-handler
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  
  # React Native Vector Icons
  # https://github.com/oblador/react-native-vector-icons
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # React Native Camera
  # https://github.com/react-native-community/react-native-camera
  pod 'react-native-camera', path: '../node_modules/react-native-camera'
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
